2021-12-19 13:50:20,706 -test_log.py[line: 42] -INFO:
    --1th log start here ********************
2021-12-19 13:50:20,708 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-19 13:50:20,709 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-19 13:50:20,709 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-19 13:50:20,710 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-19 13:50:20,711 -test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-19 13:50:20,712 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-19 13:50:20,713 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-19 13:50:20,714 -test_log.py[line: 44] -INFO:
    --≤‚ ‘Ω· ¯.
2021-12-19 13:50:22,724 -test_log.py[line: 42] -INFO:
    --2th log start here ********************
2021-12-19 13:50:22,724 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-19 13:50:22,725 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-19 13:50:22,727 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-19 13:50:22,728 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-19 13:50:22,729 -test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-19 13:50:22,731 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-19 13:50:22,732 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-19 13:50:22,732 -test_log.py[line: 44] -INFO:
    --≤‚ ‘Ω· ¯.
